const KEY="pria_goals_fixed_photo_v1";let goals=JSON.parse(localStorage.getItem(KEY)||"[]"),editingId=null,deferredPrompt=null,activeAlarmId=null,alarmTimer=null,audioCtx=null;
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(goals));render()}
function fmt(d,t){return new Date(`${d}T${t}`).toLocaleString([],{weekday:"short",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function render(){let a=[...goals].sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time));$("goalsList").innerHTML=a.length?a.map(g=>`<div class="goal ${g.completed?"completed":""}"><div><div class="goal-title">${g.completed?"✅ ":""}${esc(g.title)}</div><div class="goal-meta">🗓️ ${fmt(g.date,g.time)}</div></div><div class="goal-actions">${!g.completed?`<button class="btn primary" onclick="completeGoal('${g.id}')">✓ Complete</button>`:""}<button class="btn light" onclick="editGoal('${g.id}')">✏️ Edit</button><button class="btn danger" onclick="deleteGoal('${g.id}')">🗑️ Delete</button></div></div>`).join(""):'<p style="margin-top:18px">No goals yet. Add your first goal above.</p>';progress()}
function progress(){let a=goals.filter(g=>g.date===today()),d=a.filter(g=>g.completed).length,p=a.length?Math.round(d/a.length*100):0;$("progressText").textContent=`${d} of ${a.length} goals completed — ${p}%`;$("progressBar").style.width=p+"%";$("perfectDay").classList.toggle("hidden",!(a.length&&d===a.length))}
function form(g=null){$("goalForm").classList.remove("hidden");editingId=g?.id||null;$("goalTitle").value=g?.title||"";$("goalDate").value=g?.date||today();$("goalTime").value=g?.time||"";$("goalTitle").focus()}
$("addGoalBtn").onclick=()=>form();$("cancelGoalBtn").onclick=()=>{$("goalForm").classList.add("hidden");editingId=null};
$("saveGoalBtn").onclick=()=>{let title=$("goalTitle").value.trim(),date=$("goalDate").value,time=$("goalTime").value;if(!title||!date||!time)return alert("Please enter the goal, date and exact time.");if(editingId){let g=goals.find(x=>x.id===editingId);Object.assign(g,{title,date,time,alertedAt:null})}else goals.push({id:crypto.randomUUID(),title,date,time,completed:false,alertedAt:null});save();$("goalForm").classList.add("hidden");editingId=null};
window.completeGoal=id=>{let g=goals.find(x=>x.id===id);if(g){g.completed=true;save();if(activeAlarmId===id)closeAlarm()}};window.deleteGoal=id=>{if(confirm("Delete this goal?")){goals=goals.filter(x=>x.id!==id);save()}};window.editGoal=id=>{let g=goals.find(x=>x.id===id);if(g)form(g)};
function speak(t){if("speechSynthesis"in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u)}}
function beep(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.35)}catch(e){}}
function notify(t,b){if("Notification"in window&&Notification.permission==="granted")try{new Notification(t,{body:b,icon:"icon.svg",tag:"pria"})}catch(e){}}
$("notificationBtn").onclick=async()=>{if(!("Notification"in window))return alert("This browser does not support notifications.");let p=await Notification.requestPermission();$("status").textContent=p==="granted"?"Notifications & alarms allowed":"Notification permission not granted";if(p==="granted")speak("Notifications and alarms are enabled.")};
$("testAlarmBtn").onclick=()=>{beep();setTimeout(beep,450);speak("This is the PRIA test alarm.");$("status").textContent="Test alarm played";setTimeout(()=>$("status").textContent="Ready",2500)};
function alarm(g){activeAlarmId=g.id;$("alarmMessage").textContent=`It's time to ${g.title} now.`;$("alarmOverlay").classList.remove("hidden");notify("PRIA Reminder",`It's time to ${g.title} now.`);speak(`It's time to ${g.title} now.`);beep();clearInterval(alarmTimer);alarmTimer=setInterval(()=>{beep();speak(`It's time to ${g.title} now.`)},5000)}
function closeAlarm(){$("alarmOverlay").classList.add("hidden");clearInterval(alarmTimer);alarmTimer=null;activeAlarmId=null}
$("dismissAlarmBtn").onclick=closeAlarm;$("completeAlarmBtn").onclick=()=>{if(activeAlarmId){let g=goals.find(x=>x.id===activeAlarmId);if(g){g.completed=true;save()}}closeAlarm()};
function tick(){let n=new Date();$("clock").textContent=n.toLocaleTimeString();$("date").textContent=n.toLocaleDateString([],{weekday:"long",day:"numeric",month:"long",year:"numeric"});let m=Math.floor(n.getTime()/60000);for(let g of goals){if(g.completed)continue;let d=new Date(`${g.date}T${g.time}`);if(Math.abs(n-d)<=60000&&g.alertedAt!==m){g.alertedAt=m;localStorage.setItem(KEY,JSON.stringify(goals));alarm(g)}}let k="daily6_"+today();if(n.getHours()===6&&n.getMinutes()===0&&localStorage.getItem(k)!=="1"){localStorage.setItem(k,"1");notify("PRIA","It's time to set today's goals.");speak("It's time to set today's goals.")}}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").classList.add("hidden")}else alert("Open your browser menu and choose Install PRIA or Add to Home Screen.")};window.addEventListener("appinstalled",()=>{$("installBtn").classList.add("hidden")});if(matchMedia("(display-mode:standalone)").matches)$("installBtn").classList.add("hidden");render();tick();setInterval(tick,1000);